name: Build and deploy

on:
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

env:
  SOURCE_BRANCH: refs/heads/source

jobs:
  deploy:
    name: Deploy website
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: npm

      - name: Build assets
        run: npm run build

      - name: Generate
        run: docker run --rm -v $(pwd):/app viktoras25/sculpin:latest generate --env=live

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.ref == env.SOURCE_BRANCH }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output_live
          cname: viktoras.de
